name: glmhmmbeta
channels:
  - conda-forge
dependencies:
  - python==3.9.5
  - pip==21.3.1
  - pip:
    - matplotlib==3.3.4
    - numpy==1.23.3
    - scipy==1.9.1
    - jupyter==1.0.0
    - jupyterlab==3.4.4